Identification: var_subsetter_config
Version: 13

# A list of hdf subdataset paths that provide the shortname value of the
# collection for the data file being processed.  Processed in this order to
# find a shortname value for the current file.
Collection_ShortName_Path:
  - '/HDF5_GLOBAL/short_name'
  - '/NC_GLOBAL/short_name'
  - '/Metadata/DatasetIdentification/shortName'
  - '/METADATA/DatasetIdentification/shortName'
  - '/Metadata/SeriesIdentification/shortName'
  - '/METADATA/SeriesIdentification/shortName'
  - '/HDF5_GLOBAL/id'
  - '/NC_GLOBAL/id'

# A set of mission tagged shortname patterns defines a mission name for
# matching shortname values.
Mission:
  'ATL\d{2}': 'ICESat2'
  'GEDI_L[1234][AB]|GEDI0[1234]_[AB]': 'GEDI'
  'SPL[1234].+': 'SMAP'
  'VIIRS_NPP-.+-L2P': 'VIIRS_PO'

# If CF_Overrides and CF_Supplements are not enough VarInfo class will assume
# variables with a coordinates attribute are science variables. This setting
# provides variable path patterns for variables with coordinates references,
# which should be excluded from consideration as a science variable
Excluded_Science_Variables:
  - Applicability:
      Mission: 'ICESat2'
    Variable_Pattern:
      - '/quality_assessment/.*'
      - '/orbit_info/.*'
      - '/atlas_impulse_response/.*'

# VarInfo will calculate a set of required fields (variables, subdatasets)
# for a given science variable. This setting imposes additional contents
# for the required fields list.
Required_Fields:
  # TODO: Replace with ancillary_variable references.
  - Applicability:
      Mission: 'GEDI'
    Variable_Pattern:
      - '.*shot_number'

# Temporal subsetting typically encounters time tags in data files as
# e.g., delta_time, where the time value is relative to a "start-time"
# for the collection of datafiles, referred to as the time Epoch.
ProductEpochs:
  - Applicability:
      Mission: ICESat2
    Epoch: '2005-01-01T00:00:00.000000'
  - Applicability:
      Mission: GEDI
    Epoch: '2018-01-01T00:00:00.000000'

# The CF_References data can provide examples of adding Grid_Mapping
# attributes to science variables, as necessary for grid processing.  The
# following are variable data (subdataset, attributes only data) containing
# CF compliant grid mapping data. These can both fill in where no such
# grid_mapping variables exist, and potentially override any existing
# grid_mapping data, if imposed corrections are necessary.
Grid_Mapping_Data:
  - Grid_Mapping_Dataset_Name: 'EASE2_Global'
    grid_mapping_name: 'lambert_cylindrical_equal_area'
    standard_parallel: 30.0
    longitude_of_central_meridian: 0.0
    false_easting: 0.0
    false_northing: 0.0
  - Grid_Mapping_Dataset_Name: 'EASE2_Polar'
    grid_mapping_name: 'lambert_azimuthal_equal_area'
    longitude_of_projection_origin: 0.0
    latitude_of_projection_origin: 90.0
    false_easting: 0.0
    false_northing: 0.0

# For cases where CF references do not exist, or are invalid
# These variables have no dimension references in the HDF5 file contents
CF_Overrides:
  # the following cases are for missing grid mapping data, essential to
  # data processing.  It is difficult to properly interpret without this.
  - Applicability:
      Mission: 'SMAP'
      ShortNamePath: 'SPL4.*'
      # superfluous, except for incomplete or pre V4 SMAP data
    Attributes:
      - Name: 'Grid_Mapping'
        Value: 'EASE2_Global'
  - Applicability:
      Mission: 'SMAP'
      ShortNamePath: 'SPL3FT(P|P_E)'
    Applicability_Group:
      - Applicability:
          Variable_Pattern: '(?i).*global.*'
        Attributes:
          - Name: 'Grid_Mapping'
            Value: 'EASE2_Global'
      - Applicability:
          Variable_Pattern: '(?i).*polar.*'
        Attributes:
          - Name: 'Grid_Mapping'
            Value: 'EASE2_Polar'
  - Applicability:
      Mission: 'SMAP'
      ShortNamePath: 'SPL3FTA'
    Attributes:
      - Name: 'Grid_Mapping'
        Value: 'EASE2_Polar'
  # In the following case, the fill value in CF attributes is not what is found
  # inside the data arrays.  This is providing the correct fill value.
  - Applicability:
      Mission: 'SMAP'
      ShortNamePath: 'SPL3FT(A|P|P_E)'
      Variable_Pattern: '/Freeze_Thaw_Retrieval_Data_Polar/(latitude|longitude).*'
    Attributes:
      - Name: '_fill'
        Value: '-9999'

# For extending CF references. This allows for CF references to persist, while
# supplemental information is provided. In particular, e.g. for subsetting
# support, non-CF attributes can be provided.
CF_Supplements:  
  - Applicability:
      Mission: 'ICESat2'
      ShortNamePath: 'ATL0[3-9]|ATL1[023]' # L1/L2
    Global_Attributes:
      - Name: 'Data_Organization'
        Value: 'h5_trajectory'
       # organizations: h5_grid, h5_trajectory, h5_swath, h4eos_grid, h4eos_swath 
    Applicability_Group:
      # provide an ancillary_variable reference for these datasets
      # (ensuring treatment as "required_field")
      - Applicability:
          Variable_Pattern: '/gt[123][lr]/geolocation/.*'
        Attributes:
          - Name: 'ancillary_variables'
            Value: 'podppd_flag'
      # provide subset-control-variable designation for these datasets
      - Applicability:
          ShortNamePath: 'ATL03'
          Variable_Pattern: '/gt[123][lr]/geophys_corr/.*'
        Attributes:
          # Linking datasets for subsetting purposes; DAS-682
          - Name: 'subset_control_variables'
            Value: '../geolocation/delta_time, ../geolocation/reference_photon_lat, ../geolocation/reference_photon_lon'
          - Name: 'subset_control_type'
            Value: 'coordinates'
      - Applicability:
          ShortNamePath: 'ATL03'
          Variable_Pattern: '/gt[123][lr]/heights/.*'
        Attributes:
          - Name: 'subset_control_variables'
            Value: '../geolocation/ph_index_beg, ../geolocation/segment_ph_cnt'
          - Name: 'subset_control_type'
            Value: 'fwd_segment_index'
            # type: coordinates, fwd_segment_index, rvs_segment_index
      - Applicability:
          ShortNamePath: 'ATL03'
          Variable_Pattern: '/gt[123][lr]/geolocation/ph_index_beg'
        Attributes:
          - Name: 'subset_control_variable_type'
            Value: 'segment_index_beg'
      - Applicability:
          ShortNamePath: 'ATL03'
          Variable_Pattern: '/gt[123][lr]/geolocation/ph_ind'
        Attributes:
          - Name: 'subset_control_variable_type'
            Value: 'segment_index_cnt'
      - Applicability:
          ShortNamePath: 'ATL08'
          Variable_Pattern: '/gt[123][lr]/signal_photons/.*'
        Attributes:
          - Name: 'subset_control_variables'
            Value: '../land_segments/ph_ndx_beg, ../land_segments/n_seg_ph'
          - Name: 'subset_control_type'
            Value: 'fwd_segment_index'
      - Applicability:
          ShortNamePath: 'ATL08'
          Variable_Pattern: '/gt[123][lr]/land_segments/ph_ndx_beg'
        Attributes:
          - Name: 'subset_control_variable_type'
            Value: 'segment_index_beg'
      - Applicability:
          ShortNamePath: 'ATL08'
          Variable_Pattern: '/gt[123][lr]/land_segments/n_seg_ph'
        Attributes:
          - Name: 'subset_control_variable_type'
            Value: 'segment_index_cnt'

# ToDo ShortNamePath: ATL10
  - Applicability:
      Mission: 'GEDI'
      ShortNamePath: 'GEDI_L[1234][AB]|GEDI0[1234]_[AB]'
    Global_Attributes:
      - Name: 'Data_Organization'
        Value: 'h5_trajectory'
    Applicability_Group:
      - Applicability:
          ShortNamePath: 'GEDI_L1[AB]|GEDI01_[AB]'
          Variable_Pattern: '/BEAM[\d]+/geolocation/'
        Attributes:
          # Resetting the spatial coordinates for subsetting purposes
          - Name: 'subset_control_variables'
            Value: 'delta_time, latitude_bin0, longitude_bin0'
          - Name: 'subset_control_type'
            Value: 'coordinates'
      - Applicability:
          ShortNamePath: 'GEDI_L2A|GEDI02_A'
          Variable_Pattern: '/BEAM[\d]+/'
        Attributes:
          # Resetting the spatial coordinates for subsetting purposes
          - Name: 'subset_control_variables'
            Value: 'lat_lowestmode, lon_lowestmode, delta_time'
          - Name: 'subset_control_type'
            Value: 'coordinates'
      - Applicability:
          ShortNamePath: 'GEDI_L2A|GEDI02_A'
          Variables: '/BEAM[\d]+/geolocation/'
        Attributes:
          # Resetting the spatial coordinates for subsetting purposes
          - Name: 'subset_control_variables'
            Value': 'lat_lowestmode, lon_lowest_mode, delta_time'
          - Name: 'subset_control_type'
            Value: 'coordinates'
      # Provide index segment subset-control designation for these dataset
      - Applicability:
          ShortNamePath: 'GEDI_L1[AB]|GEDI01_[AB]'
          Variables: '/BEAM[\\d]+/rxwaveform'
        Attributes:
          - Name: 'subset_control_variables'
            Value: 'rx_sample_start_index, rx_sample_count'
          - Name: 'subset_control_type'
            Value: 'fwd_segment_index'
      - Applicability:
          ShortNamePath: 'GEDI_L1[AB]|GEDI01_[AB]'
          Variables: '/BEAM[\\d]+/rx_sample_start_index'
        Attributes:
          - Name: 'subset_control_variable_type'
            Value: 'segment_index_beg'
      - Applicability:
          ShortNamePath: 'GEDI_L1[AB]|GEDI01_[AB]'
          Variable_Pattern: '/BEAM[\\d]+/rx_sample_count'
        Attributes:
          - Name: 'subset_control_variable_type'
            Value: 'segment_index_cnt'
      - Applicability:
          ShortNamePath: 'GEDI_L1[AB]|GEDI01_[AB]'
          Variables: '/BEAM[\\d]+/txwaveform'
        Attributes:
          - Name: 'subset_control_variables'
            Value: 'tx_sample_start_index, tx_sample_count'
        Attributes:
          - Name: 'subset_control_type'
            Value: 'fwd_segment_index'
      - Applicability:
          ShortNamePath: 'GEDI_L1[AB]|GEDI01_[AB]'
          Variables: '/BEAM[\\d]+/tx_sample_start_index'
        Attributes:
          - Name: 'subset_control_variable_type'
            Value: 'segment_index_beg'
      - Applicability:
          ShortNamePath: 'GEDI_L1[AB]|GEDI01_[AB]'
          Variable_Pattern: '/BEAM[\\d]+/tx_sample_count'
        Attributes:
          - Name: 'subset_control_variable_type'
            Value: 'segment_index_cnt'
      - Applicability:
          ShortNamePath: 'GEDI_L2B|GEDI02_B'
          Variables: '/BEAM[\\d]+/pgap_theta_z'
        Attributes:
          - Name: 'subset_control_variables'
            Value: 'rx_sample_start_index, rx_sample_count'
          - Name: 'subset_control_type'
            Value: 'fwd_segment_index'
      - Applicability:
          ShortNamePath: 'GEDI_L2B|GEDI02_B'
          Variables: '/BEAM[\\d]+/rx_sample_start_index'
        Attributes:
          - Name: 'subset_control_variable_type'
            Value: 'segment_index_beg'
      - Applicability:
          ShortNamePath: 'GEDI_L2B|GEDI02_B'
          Variable_Pattern: '/BEAM[\\d]+/rx_sample_count'
        Attributes:
          - Name: 'subset_control_variable_type'
            Value: 'segment_index_cnt'
